add language module
MalpenZibo/ashell pull request #72
Opened 2024-11-17 15:51 UTC by fiersik

## Description 
A simple module for displaying the current keyboard layout

![image](https://github.com/user-attachments/assets/0fdefaff-f07d-4f13-892c-6327afcc255a)

## Functionality 
- Display of the current layout
- Switching the layout by clicking on the module 

The module is displayed only if more than one keyboard layout is installed, but if necessary, it can be forcibly hidden 
```
language:
    disabled: true
```

2024-11-17 16:06 UTC, fiersik commented
Checking the code is my main enemy (

2024-11-17 16:27 UTC, fiersik commented
Hooray, I passed the tests

2024-11-17 19:05 UTC, MalpenZibo commented
Very nice! Thanks for submitting new features :) Recently I don't have too much time but I will try to review you code as soon as I can.

2024-11-17 20:34 UTC, fiersik commented
> Thanks for submitting new features :)

It's more fun together!

> but I will try to review you code as soon as I can.

okay, I'll think about how to improve this module for now.) 
Alas, this PR conflicts with the tray branch

2024-11-19 23:36 UTC, fiersik commented
I have another idea!

2024-11-19 23:39 UTC, fiersik commented
ouch...

2024-11-20 08:48 UTC, MalpenZibo requested changes
Very nice! I left some comments about the name of the module, I prefer something that better indicates that this is a switch to change the Keyboard layout and not the system language, and some performance stuff

2024-11-20 08:48 UTC, MalpenZibo commented on src/app.rs
> +    language: Language,
here I prefer something like `KeyboardLayout` for the name of the module and the struct

2024-11-20 08:48 UTC, MalpenZibo commented on src/modules/language.rs
> +}
```suggestion
pub struct KeyboardLayout {
    layouts: Vec<(String, bool)>, // the bool indicate if it's active otherwise we could create a new struct { layout: String, active: bool }
}
```

2024-11-20 08:48 UTC, MalpenZibo commented on src/modules/language.rs
> +    ChangeLanguage(),
```suggestion
    ChangeLanguage,
```

2024-11-20 08:48 UTC, MalpenZibo commented on src/modules/language.rs
> +        let layout_list: Vec<&str> = layouts.split(',').collect();
For performance reason I prefer to move this logic to the subscription, maybe we could change the `get_active_keymap` to return a `Vec<Layout>` where Layout is something like
```
struct Layout {
  layout: String,
  active: bool
}
```

2024-11-20 08:48 UTC, MalpenZibo commented on src/modules/language.rs
> +    pub fn subscription(&self) -> Subscription<Message> {
I will move all the possible logic here. The `LanguageChanged` message should contain the list of all possible kb_layouts and the active one.

2024-11-20 08:48 UTC, MalpenZibo commented on src/modules/language.rs
> +    let keyboards = hyprland::data::Devices::get().unwrap().keyboards;
Let's try to avoid `unwrap.` We should choose between returning a default value and an Option. In this case, I cannot think of a sane default value, so maybe it's better to return an Option.

2024-11-20 10:31 UTC, fiersik commented
Thank you very much! I will try to take into account all the suggestions.

2024-11-20 16:23 UTC, fiersik commented
I didn't use all the suggestions, however, I definitely improved the code.

2024-11-20 17:10 UTC, MalpenZibo requested changes
Nice! we're almost there :rocket:

2024-11-20 17:10 UTC, MalpenZibo commented on src/app.rs
> +                )
```suggestion
                .push_maybe(
                        self.keyboard_layout
                            .view(&self.config.keyboard.layout)
                            .map(|l| l.map(Message::KeyboardLayout)),
                )
```

2024-11-20 17:10 UTC, MalpenZibo commented on src/config.rs
> +
Why have you created a nested struct? Something like
```
#[derive(Deserialize, Clone, Default, Debug)]
#[serde(rename_all = "camelCase")]
pub struct KeyboardModuleConfig {
    #[serde(default)]
    pub disabled: bool,
}
```
is not enough?

2024-11-20 17:10 UTC, MalpenZibo commented on src/modules/keyboard_layout.rs
> +                event_listener.add_layout_changed_handler({
Here we should also listen to hyprland config changes
```
                event_listener.add_config_reloaded_handler({
                    let output = output.clone();
                    move || {
                        let output = output.clone();
                        Box::pin(async move {
                            if let Ok(mut output) = output.write() {
                                output
                                    .try_send(Message::LayoutConfigChanged)
                                    .expect("error sending message: layout config changed event");
                            }
                        })
                    }
                });

```

2024-11-20 17:10 UTC, MalpenZibo commented on src/modules/keyboard_layout.rs
> +                button(text(self.layout.active.clone()))
```suggestion
                button(text(&self.layout.active))
```

2024-11-20 17:10 UTC, MalpenZibo commented on src/modules/keyboard_layout.rs
> +    }
Now I understand better the problem.

In the end, maybe we should split this function into two: one to get the active keyboard layout and one to get a flag indicating if there are more than two possible keyboard layouts. 

The first one should be used during module initialization and when we receive a hyprland config changes event, and the second during the module init and when we receive a hyprland layout changed event.

Here's an example
```
fn get_multiple_layout_flag() -> bool {
    match hyprland::keyword::Keyword::get("input:kb_layout") {
        Ok(layouts) => layouts.value.to_string().split(",").count() > 1, //In this way we skip the collect to avoid useless string allocation
        Err(_) => false,
    }
}

fn get_active_layout() -> String {
    hyprland::data::Devices::get()
        .ok()
        .and_then(|devices| {
            devices
                .keyboards
                .iter()
                .find(|k| k.main)
                .map(|keyboard| keyboard.active_keymap.to_string())
        })
        .unwrap_or_else(|| "unknown".to_string())
}

```

2024-11-20 17:10 UTC, MalpenZibo commented on src/modules/keyboard_layout.rs
> +}
This could be simplified into (feel free to change names)
```suggestion
#[derive(Debug, Clone)]
pub struct KeyboardLayout {
    multiple_layout: bool,
    active: String,
}

impl Default for KeyboardLayout {
    fn default() -> Self {
        Self {
            multiple_layout: get_multiple_layout_flag(),
            active: get_active_layout(),
        }
    }
}
```

2024-11-20 17:10 UTC, MalpenZibo commented on src/modules/keyboard_layout.rs
> +}
```suggestion
pub enum Message {
    LayoutConfigChanged,
    ActiveLayoutChanged(String),
    ChangeLayout,
}
```

2024-11-20 17:10 UTC, MalpenZibo commented on src/modules/keyboard_layout.rs
> +        if config.disabled || self.layout.num_layouts < 2 {
with the other change this could become
```suggestion
  if config.disabled || !self.multiple_layout 
```

2024-11-20 17:32 UTC, fiersik commented
regarding the first few amendments...

The nested config is made specifically and will be used for another module `keyboard_submap`
The nested Row::new() is made for the same purpose

They should not be cleaned

2024-11-20 17:48 UTC, MalpenZibo commented
> regarding the first few amendments...
> 
> The nested config is made specifically and will be used for another module `keyboard_submap` The nested Row::new() is made for the same purpose
> 
> They should not be cleaned

Ah okok, so you plan to add additional features in this PR? Ok!

2024-11-20 17:49 UTC, fiersik commented on src/modules/keyboard_layout.rs
> +    }
> and when we receive a hyprland config changes event,

When changing the `input` configuration, the keyboard layout update event comes, so it doesn't make much sense.

Both functions will still be called.

2024-11-20 17:52 UTC, fiersik commented
> so you plan to add additional features in this PR?

Yes! But here the task is more interesting, we need to output data that cannot be requested in the usual way, we will have to take it directly from the event

2024-11-20 18:57 UTC, fiersik commented
I corrected a few sentences, but left the code that may be useful to me in the future.

2024-11-20 20:47 UTC, fiersik commented
Great, I'm waiting for the latest checks and it will be possible to update the README and changelog

Now it looks like this:
![image](https://github.com/user-attachments/assets/aef480fe-f631-4626-aa13-dca27ba17689)
Modules are displayed only if they are needed, hidden if necessary

2024-11-21 17:04 UTC, MalpenZibo commented
@fiersik ok, if you have finished with the PR make it ready to review and I will do the final review and test

2024-11-21 17:52 UTC, fiersik commented
I think I've done everything I wanted to do.

2024-11-22 12:52 UTC, MalpenZibo approved these changes
:rocket: Thanks for the effort.

Just a minor comment but it's more than ok as it is!

2024-11-22 12:52 UTC, MalpenZibo commented on src/modules/keyboard_submap.rs
> +                event_listener.add_sub_map_changed_handler({
I don't know if we want to listen to Hyland config changes here. (Maybe it's too much; I don't really know.)

2024-11-22 13:01 UTC, fiersik commented
submap is configuration independent, so I don't see the point in tracking configuration changes.

2024-11-22 14:51 UTC, fiersik commented
well...Are there any amendments?
I think everything is ready here

2024-11-22 16:02 UTC, merged

2024-11-22 16:56 UTC, fiersik commented
Thanks :)